-- Merge legacy zhgl CAT-* equipment categories into EQCAT-* standard library
-- Generated by migrate_legacy_cat_to_eqcat.py
SET search_path TO dynamicbusiness;

-- temp: old CAT code -> target category code (leaf or nearest node)
CREATE TEMP TABLE legacy_cat_map (old_code text PRIMARY KEY, target_code text NOT NULL);
INSERT INTO legacy_cat_map (old_code, target_code) VALUES
;

-- 1) migrate model-category relations from CAT to EQCAT
UPDATE dynamic_model_category_relation r
SET
  category_id = nc.id,
  category_code = nc.code,
  updater = 'migrate-legacy-cat',
  update_time = CURRENT_TIMESTAMP
FROM legacy_cat_map m
JOIN dynamic_category oc
  ON oc.deleted = false AND oc.tenant_id = 1 AND oc.code = m.old_code
JOIN dynamic_category nc
  ON nc.deleted = false AND nc.tenant_id = 1 AND nc.code = m.target_code
WHERE r.deleted = false AND r.tenant_id = 1
  AND r.entity_type_code = 'equipment'
  AND r.category_id = oc.id
  AND r.category_code = oc.code;

-- 2) legacy MODEL-* refined mapping by model name
UPDATE dynamic_model_category_relation r
SET
  category_id = nc.id,
  category_code = nc.code,
  updater = 'migrate-legacy-cat',
  update_time = CURRENT_TIMESTAMP
FROM dynamic_model dm
JOIN (
  VALUES
    ('给水泵', 'EQCAT-DEV-PUMP-SUPPLY'), ('门禁', 'EQCAT-DEV-ACCESS-CTRL'), ('应急灯', 'EQCAT-DEV-EMERGENCY-LIGHT'), ('二氧化碳检测仪', 'EQCAT-DEV-SENSOR-CO2'), ('温湿度检测仪', 'EQCAT-DEV-SENSOR-TH'), ('温湿度传感器', 'EQCAT-DEV-SENSOR-TH')
) AS mm(model_name, target_code) ON mm.model_name = dm.name
JOIN dynamic_category nc
  ON nc.deleted = false AND nc.tenant_id = 1 AND nc.code = mm.target_code
WHERE r.deleted = false AND r.tenant_id = 1
  AND r.entity_type_code = 'equipment'
  AND r.model_id = dm.id
  AND dm.deleted = false AND dm.entity_type_code = 'equipment'
  AND dm.code LIKE 'MODEL-%';

-- 3) remove leftover CAT relations
-- 4) soft-delete legacy CAT categories
-- 5) rebuild tree_path
UPDATE dynamic_model_category_relation r
SET deleted = true, updater = 'migrate-legacy-cat', update_time = CURRENT_TIMESTAMP
WHERE r.deleted = false AND r.tenant_id = 1
  AND r.entity_type_code = 'equipment'
  AND r.category_code LIKE 'CAT-%';

-- 4) 软删旧 CAT-* 分类
UPDATE dynamic_category c
SET deleted = true, updater = 'migrate-legacy-cat', update_time = CURRENT_TIMESTAMP
WHERE c.deleted = false AND c.tenant_id = 1
  AND c.category_type_code = 'equipment'
  AND c.code LIKE 'CAT-%';

-- 5) 重建树路径
WITH RECURSIVE cat_tree AS (
  SELECT c.id, c.code, c.parent_id, ARRAY[c.id] AS path_ids, 0 AS lvl
  FROM dynamic_category c
  WHERE c.deleted = false AND c.tenant_id = 1
    AND c.category_type_code = 'equipment'
    AND (c.parent_id IS NULL OR c.parent_id = 0
         OR NOT EXISTS (
           SELECT 1 FROM dynamic_category p
           WHERE p.id = c.parent_id AND p.deleted = false AND p.tenant_id = 1
         ))
  UNION ALL
  SELECT c.id, c.code, c.parent_id, ct.path_ids || c.id, ct.lvl + 1
  FROM dynamic_category c
  JOIN cat_tree ct ON c.parent_id = ct.id
  WHERE c.deleted = false AND c.tenant_id = 1
    AND c.category_type_code = 'equipment'
)
UPDATE dynamic_category c
SET tree_path = ct.path_ids, level = ct.lvl + 1
FROM cat_tree ct
WHERE c.id = ct.id AND c.category_type_code = 'equipment';
