package cn.cheers.x.module.dynamicbusiness.dal.dataobject.model;

import cn.cheers.x.framework.tenant.core.db.TenantBaseDO;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.KeySequence;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.*;

/**
 * Model 关联 DO（系统执行层）
 * 
 * 业务含义：存储 Model 之间的关联关系，由系统根据 EntityType 关联自动生成。
 * 
 * 两层关联架构：
 * 1. 第一层（用户操作层）：EntityType 级别关联，存储在 dynamic_entity_type_relation 表
 * 2. 第二层（系统执行层）：Model 级别关联，存储在此表
 * 
 * 关联来源：
 * - auto_generated=true：由系统根据 EntityType 关联自动生成
 * - auto_generated=false：手动创建的 Model 关联
 * 
 * 关联字段：
 * - 系统自动为源 Model 创建关联字段（ENTITY_REF 类型）
 * - 字段编码规则：目标 Model 编码 + "_id"（如 plan_id）
 * - 字段名称规则："所属" + 目标 Model 名称（如"所属计划"）
 * 
 * 查询能力：
 * - 正向查询：查询某计划的所有任务
 * - 反向查询：查询某任务属于哪个计划
 * - 关联统计：统计每个计划下的任务数量
 * 
 * @author yudao
 */
@TableName("dynamic_model_relation")
@KeySequence("dynamic_model_relation_seq")
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ModelRelationDO extends TenantBaseDO {

    /**
     * 主键
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 来源的 EntityType 关联 ID
     * 
     * 可为空，表示手动创建的 Model 关联
     */
    private Long entityTypeRelationId;

    /**
     * 源 Model ID
     */
    private Long sourceModelId;

    /**
     * 源 Model 编码
     */
    private String sourceModelCode;

    /**
     * 目标 Model ID
     */
    private Long targetModelId;

    /**
     * 目标 Model 编码
     */
    private String targetModelCode;

    /**
     * 关联名称
     * 
     * 如：所属计划
     */
    private String relationName;

    /**
     * 关联字段编码
     * 
     * 如：plan_id
     */
    private String fieldCode;

    /**
     * 是否系统自动生成
     * 
     * true：由系统根据 EntityType 关联自动生成
     * false：手动创建的 Model 关联
     * 
     * 注意：使用 Lombok 生成的 getAutoGenerated() 方法，避免与 MyBatis 的 Boolean 类型 getter 规则冲突
     * 如果需要判断是否为自动生成，使用：Boolean.TRUE.equals(getAutoGenerated())
     */
    private Boolean autoGenerated;

    /**
     * 判断是否为手动创建的关联
     */
    public boolean isManualCreated() {
        return !Boolean.TRUE.equals(this.autoGenerated);
    }
}
