spring:
  application:
    name: work-order-server

  profiles:
    active: local

  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Feign 等会存在重复定义的服务

  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml # 加载【本地】配置
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml # 加载【Nacos】的配置

  # Servlet 配置
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小

  # Jackson 配置项
  jackson:
    serialization:
      write-dates-as-timestamps: true # 设置 LocalDateTime 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式
      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false # 允许序列化无属性的 Bean

  # Cache 配置项
  cache:
    type: REDIS
    redis:
      time-to-live: 1h # 设置过期时间为 1 小时

server:
  port: 58098

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log # 日志文件名，全路径

--- #################### 接口文档配置 ####################

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn

# MyBatis Plus 的配置项
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: NONE
      logic-delete-value: true
      logic-not-delete-value: false
    banner: false
  type-aliases-package: cn.cheers.x.workorder.dal.dataobject
  encryptor:
    password: XDV71a+xqStEA3WH

mybatis-plus-join:
  banner: false

# Spring Data Redis 配置
spring:
  data:
    redis:
      repositories:
        enabled: false

# VO 转换（数据翻译）相关
easy-trans:
  is-enable-global: false

--- #################### RPC 远程调用相关配置 ####################

--- #################### Cheers 相关配置 ####################

cheers:
  info:
    version: 1.0.0
    base-package: cn.cheers.x.workorder
  web:
    admin-ui:
      url: http://dashboard.local
  xss:
    enable: false
    exclude-urls:
      - ${management.endpoints.web.base-path}/**
  swagger:
    title: 工单管理
    description: 提供工单管理的所有功能
    version: ${cheers.info.version}
  tenant:
    enable: true
    ignore-urls:
    ignore-visit-urls:
    ignore-tables:
    ignore-caches:

debug: false
