package cn.cheers.x.module.dynamicbusiness.service.model;

import cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder;

import cn.cheers.x.module.dynamicbusiness.controller.admin.model.vo.CustomRelationFieldCreateReqVO;
import cn.cheers.x.module.dynamicbusiness.dal.dataobject.field.FieldDO;
import cn.cheers.x.module.dynamicbusiness.dal.dataobject.model.ModelDO;
import cn.cheers.x.module.dynamicbusiness.dal.dataobject.model.ModelFieldAssignmentDO;
import cn.cheers.x.module.dynamicbusiness.dal.dataobject.model.ModelRelationDO;
import cn.cheers.x.module.dynamicbusiness.dal.dataobject.relation.ModelRelationDeclarationDO;
import cn.cheers.x.module.dynamicbusiness.dal.mysql.model.ModelMapper;
import cn.cheers.x.module.dynamicbusiness.dal.mysql.model.ModelRelationMapper;
import cn.cheers.x.module.dynamicbusiness.dal.mysql.relation.ModelRelationDeclarationMapper;
import cn.cheers.x.module.dynamicbusiness.service.relation.RelationFieldCodes;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import jakarta.annotation.Resource;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import static cn.iocoder.yudao.framework.common.exception.util.ServiceExceptionUtil.exception;
import static cn.cheers.x.module.dynamicbusiness.enums.ErrorCodeConstants.*;

/**
 * Model 关联服务实现
 * 
 * 业务含义：管理 Model 之间的关联关系，支持正向查询和反向查询。
 * 
 * 关联字段自动创建：
 * - 在建立关联时，系统自动为源 Model 和目标 Model 创建关联字段（ENTITY_REF_MULTI 类型，支持List）
 * - 字段编码规则：目标 Model 编码 + "_id"（如 plan_id）
 * - 字段名称规则："关联" + 目标 Model 名称（如"关联计划"）
 * - 字段类型：ENTITY_REF_MULTI（支持同时关联多个对象）
 * - 字段自动设置为可查询（is_searchable=true）
 * 
 * 需求：FR-075, FR-076, FR-080, BR-REL-001, BR-REL-002, BR-REL-003
 * 
 * @author yudao
 */
@Service
@Validated
@Slf4j
public class ModelRelationServiceImpl implements ModelRelationService {

    @Resource
    private ModelRelationMapper modelRelationMapper;

    @Resource
    private ModelMapper modelMapper;

    @Resource
    @Lazy // 避免循环依赖
    private ModelFieldAssignmentService modelFieldAssignmentService;

    @Resource
    private ModelRelationDeclarationMapper modelRelationDeclarationMapper;

    @Override
    @Transactional(rollbackFor = Exception.class)
    public Long createRelation(String sourceModelCode, String targetModelCode,
                               String relationName, Boolean autoGenerated, Long entityTypeRelationId) {
        // 1. 验证源 Model 存在
        ModelDO sourceModel = modelMapper.selectByCode(sourceModelCode);
        if (sourceModel == null) {
            throw exception(MODEL_NOT_EXISTS);
        }

        // 2. 验证目标 Model 存在
        ModelDO targetModel = modelMapper.selectByCode(targetModelCode);
        if (targetModel == null) {
            throw exception(MODEL_NOT_EXISTS);
        }

        // 3. 检查关联是否已存在
        if (modelRelationMapper.existsBySourceAndTargetModelId(sourceModel.getId(), targetModel.getId())) {
            log.warn("Model 关联已存在: {} -> {}", sourceModelCode, targetModelCode);
            // 返回已存在的关联 ID
            ModelRelationDO existingRelation = modelRelationMapper.selectBySourceAndTargetModelId(
                    sourceModel.getId(), targetModel.getId());
            return existingRelation.getId();
        }

        // 4. 生成关联名称（如果未提供）
        String finalRelationName = relationName;
        if (finalRelationName == null || finalRelationName.isEmpty()) {
            finalRelationName = generateRelationName(targetModel);
        }

        // 5. 生成关联字段编码
        String fieldCode = generateFieldCode(targetModel);

        // 6. 创建 Model 关联
        ModelRelationDO relation = ModelRelationDO.builder()
                .entityTypeRelationId(entityTypeRelationId)
                .sourceModelId(sourceModel.getId())
                .sourceModelCode(sourceModelCode)
                .targetModelId(targetModel.getId())
                .targetModelCode(targetModelCode)
                .relationName(finalRelationName)
                .fieldCode(fieldCode)
                .autoGenerated(autoGenerated != null ? autoGenerated : false)
                .build();

        modelRelationMapper.insert(relation);
        log.info("创建 Model 关联成功: {} -> {}, fieldCode={}", sourceModelCode, targetModelCode, fieldCode);

        // 7. 自动创建关联字段（需求：FR-076, BR-REL-002, BR-REL-003）
        // 7.1 创建source model的REF字段（指向target model）
        try {
            createRelationField(sourceModel, targetModel, fieldCode, finalRelationName, relation.getId());
        } catch (Exception e) {
            log.error("创建source model关联字段失败: {} -> {}, fieldCode={}", sourceModelCode, targetModelCode, fieldCode, e);
            // 关联字段创建失败不影响关联创建，记录日志即可
        }

        // 7.2 创建target model的REF字段（指向source model，双向关联）
        try {
            String reverseFieldCode = generateReverseFieldCode(sourceModel);
            String reverseRelationName = generateReverseRelationName(sourceModel);
            createRelationField(targetModel, sourceModel, reverseFieldCode, reverseRelationName, relation.getId());
            log.info("创建target model关联字段成功: {} -> {}, fieldCode={}", targetModelCode, sourceModelCode, reverseFieldCode);
        } catch (Exception e) {
            log.error("创建target model关联字段失败: {} -> {}, fieldCode={}", targetModelCode, sourceModelCode, e);
            // 反向关联字段创建失败不影响关联创建，记录日志即可
        }

        return relation.getId();
    }

    /**
     * 自动创建关联字段（支持字段复用和数据修复）
     * 
     * 业务关联流程优化：传递 modelRelationId 和关联目标信息
     * 
     * 数据修复逻辑（需求 7.5）：
     * - 检测字段存在但 ModelFieldAssignment 缺失的情况
     * - 检测 ModelFieldAssignment 存在但关联信息缺失的情况
     * - 自动修复不一致数据并记录日志
     * 
     * @param sourceModel 源 Model
     * @param targetModel 目标 Model
     * @param fieldCode 字段编码
     * @param fieldName 字段名称
     * @param modelRelationId Model 关联 ID
     */
    private void createRelationField(ModelDO sourceModel, ModelDO targetModel, 
                                     String fieldCode, String fieldName, Long modelRelationId) {
        // 1. 确保 Model 已声明对目标业务类型的关联（修复：创建关联字段前先创建关联声明）
        if (!modelRelationDeclarationMapper.existsByModelIdAndTarget(
                sourceModel.getId(), targetModel.getEntityTypeCode())) {
            ModelRelationDeclarationDO declaration = ModelRelationDeclarationDO.builder()
                    .modelId(sourceModel.getId())
                    .modelCode(sourceModel.getCode())
                    .targetEntityType(targetModel.getEntityTypeCode())
                    .build();
            declaration.setTenantId(getTenantId());
            modelRelationDeclarationMapper.insert(declaration);
            log.info("自动创建关联声明: modelId={}, targetEntityType={}", 
                    sourceModel.getId(), targetModel.getEntityTypeCode());
        }

        // 2. 检测并修复数据不一致情况（需求 7.5）
        DataRepairResult repairResult = detectAndRepairInconsistentData(
                sourceModel, targetModel, fieldCode, fieldName, modelRelationId);
        
        if (repairResult.isRepaired()) {
            // 数据已修复，无需创建新字段
            log.info("数据修复完成，无需创建新字段: modelId={}, fieldCode={}, repairType={}, assignmentId={}", 
                    sourceModel.getId(), fieldCode, repairResult.getRepairType(), repairResult.getAssignmentId());
            return;
        }

        // 3. 构建自定义关联字段创建请求
        CustomRelationFieldCreateReqVO reqVO = new CustomRelationFieldCreateReqVO();
        reqVO.setModelId(sourceModel.getId());
        reqVO.setFieldName(fieldName);
        reqVO.setFieldCode(fieldCode);
        reqVO.setDescription("系统自动创建的关联字段，关联到 " + targetModel.getName());
        reqVO.setRequired(false);
        reqVO.setSort(999); // 排在最后
        reqVO.setSyncToLibrary(false); // 不同步到字段库
        // 业务关联流程优化：传递 modelRelationId
        reqVO.setModelRelationId(modelRelationId);

        // 4. 调用 ModelFieldAssignmentService 创建关联字段
        Long assignmentId = modelFieldAssignmentService.createCustomRelationField(reqVO);
        log.info("自动创建关联字段成功: modelId={}, fieldCode={}, assignmentId={}, modelRelationId={}", 
                sourceModel.getId(), fieldCode, assignmentId, modelRelationId);
    }

    /**
     * 检测并修复数据不一致情况（需求 7.5）
     * 
     * 检测以下不一致情况：
     * 1. 字段存在但 ModelFieldAssignment 缺失
     * 2. ModelFieldAssignment 存在但关联信息缺失（modelRelationId、targetEntityType、targetModelCode）
     * 3. 字段和 ModelFieldAssignment 都存在但关联信息不完整
     * 
     * @param sourceModel 源 Model
     * @param targetModel 目标 Model
     * @param fieldCode 字段编码
     * @param fieldName 字段名称
     * @param modelRelationId Model 关联 ID
     * @return 修复结果
     */
    private DataRepairResult detectAndRepairInconsistentData(ModelDO sourceModel, ModelDO targetModel,
                                                              String fieldCode, String fieldName, 
                                                              Long modelRelationId) {
        String fullFieldCode = RelationFieldCodes.toModelFieldCode(fieldCode);
        
        // 1. 检查字段是否已存在
        FieldDO existingField = modelFieldAssignmentService.findFieldByCode(fullFieldCode);
        
        if (existingField == null) {
            // 字段不存在，无需修复
            return DataRepairResult.noRepairNeeded();
        }
        
        log.info("[数据修复检测] 发现已存在的字段: fieldId={}, fieldCode={}", 
                existingField.getId(), fullFieldCode);
        
        // 2. 检查 ModelFieldAssignment 是否存在
        ModelFieldAssignmentDO existingAssignment = modelFieldAssignmentService
                .findAssignmentByModelIdAndFieldId(sourceModel.getId(), existingField.getId());
        
        if (existingAssignment == null) {
            // 情况1：字段存在但 ModelFieldAssignment 缺失
            log.warn("[数据修复] 字段存在但 ModelFieldAssignment 缺失: modelId={}, fieldId={}, fieldCode={}",
                    sourceModel.getId(), existingField.getId(), fullFieldCode);
            
            // 创建新的 ModelFieldAssignment 并填充完整的关联信息
            Long assignmentId = modelFieldAssignmentService.createAssignmentForExistingField(
                    sourceModel.getId(),
                    existingField.getId(),
                    modelRelationId
            );
            
            log.info("[数据修复完成] 为已存在的字段创建 ModelFieldAssignment: " +
                    "modelId={}, fieldId={}, assignmentId={}, modelRelationId={}",
                    sourceModel.getId(), existingField.getId(), assignmentId, modelRelationId);
            
            return DataRepairResult.repaired("FIELD_EXISTS_ASSIGNMENT_MISSING", assignmentId);
        }
        
        // 3. 检查 ModelFieldAssignment 的关联信息是否完整
        boolean needsRepair = false;
        StringBuilder repairDetails = new StringBuilder();
        
        if (existingAssignment.getModelRelationId() == null) {
            needsRepair = true;
            repairDetails.append("modelRelationId缺失;");
        }
        
        if (needsRepair) {
            // 情况2/3：ModelFieldAssignment 存在但关联信息不完整
            log.warn("[数据修复] ModelFieldAssignment 关联信息不完整: assignmentId={}, 问题={}", 
                    existingAssignment.getId(), repairDetails);
            
            // 更新关联信息
            modelFieldAssignmentService.updateAssignmentRelationInfo(
                    existingAssignment.getId(),
                    modelRelationId
            );
            
            log.info("[数据修复完成] 更新 ModelFieldAssignment 关联信息: " +
                    "assignmentId={}, modelRelationId={}",
                    existingAssignment.getId(), modelRelationId);
            
            return DataRepairResult.repaired("ASSIGNMENT_RELATION_INFO_INCOMPLETE", existingAssignment.getId());
        }
        
        // 4. 数据完整，检查是否需要更新 modelRelationId（可能是重新建立关联）
        if (!Objects.equals(existingAssignment.getModelRelationId(), modelRelationId)) {
            log.info("[数据修复] 更新 ModelFieldAssignment 的 modelRelationId: " +
                    "assignmentId={}, oldModelRelationId={}, newModelRelationId={}",
                    existingAssignment.getId(), existingAssignment.getModelRelationId(), modelRelationId);
            
            modelFieldAssignmentService.updateAssignmentRelationInfo(
                    existingAssignment.getId(),
                    modelRelationId
            );
            
            return DataRepairResult.repaired("MODEL_RELATION_ID_UPDATED", existingAssignment.getId());
        }
        
        // 数据完全一致，复用现有字段
        log.info("[数据复用] 字段和 ModelFieldAssignment 已存在且数据完整: " +
                "modelId={}, fieldId={}, assignmentId={}",
                sourceModel.getId(), existingField.getId(), existingAssignment.getId());
        
        return DataRepairResult.repaired("FIELD_REUSED", existingAssignment.getId());
    }

    /**
     * 数据修复结果
     */
    private static class DataRepairResult {
        private final boolean repaired;
        private final String repairType;
        private final Long assignmentId;
        
        private DataRepairResult(boolean repaired, String repairType, Long assignmentId) {
            this.repaired = repaired;
            this.repairType = repairType;
            this.assignmentId = assignmentId;
        }
        
        public static DataRepairResult noRepairNeeded() {
            return new DataRepairResult(false, null, null);
        }
        
        public static DataRepairResult repaired(String repairType, Long assignmentId) {
            return new DataRepairResult(true, repairType, assignmentId);
        }
        
        public boolean isRepaired() {
            return repaired;
        }
        
        public String getRepairType() {
            return repairType;
        }
        
        public Long getAssignmentId() {
            return assignmentId;
        }
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void deleteRelation(String sourceModelCode, String targetModelCode) {
        // 1. 验证源 Model 存在
        ModelDO sourceModel = modelMapper.selectByCode(sourceModelCode);
        if (sourceModel == null) {
            throw exception(MODEL_NOT_EXISTS);
        }

        // 2. 验证目标 Model 存在
        ModelDO targetModel = modelMapper.selectByCode(targetModelCode);
        if (targetModel == null) {
            throw exception(MODEL_NOT_EXISTS);
        }

        // 3. 查找并删除关联
        ModelRelationDO relation = modelRelationMapper.selectBySourceAndTargetModelId(
                sourceModel.getId(), targetModel.getId());
        if (relation != null) {
            // 业务关联流程优化：级联删除相关的字段分配（需求 2.2, 4.2）
            int deletedCount = modelFieldAssignmentService.deleteByModelRelationId(relation.getId());
            log.info("级联删除字段分配: modelRelationId={}, deletedCount={}", relation.getId(), deletedCount);
            
            modelRelationMapper.deleteById(relation.getId());
            log.info("删除 Model 关联成功: {} -> {}", sourceModelCode, targetModelCode);
        } else {
            log.warn("Model 关联不存在: {} -> {}", sourceModelCode, targetModelCode);
        }
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void deleteRelationById(Long id) {
        ModelRelationDO relation = modelRelationMapper.selectById(id);
        if (relation != null) {
            // 业务关联流程优化：级联删除相关的字段分配（需求 2.2, 4.2）
            int deletedCount = modelFieldAssignmentService.deleteByModelRelationId(id);
            log.info("级联删除字段分配: modelRelationId={}, deletedCount={}", id, deletedCount);
            
            modelRelationMapper.deleteById(id);
            log.info("删除 Model 关联成功: id={}, {} -> {}", 
                    id, relation.getSourceModelCode(), relation.getTargetModelCode());
        }
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public int deleteByEntityTypeRelationId(Long entityTypeRelationId) {
        int count = modelRelationMapper.deleteByEntityTypeRelationId(entityTypeRelationId);
        log.info("根据 EntityType 关联 ID 删除 Model 关联: entityTypeRelationId={}, count={}", 
                entityTypeRelationId, count);
        return count;
    }

    @Override
    public List<ModelRelationDO> getRelationsBySourceModelCode(String sourceModelCode) {
        return modelRelationMapper.selectBySourceModelCode(sourceModelCode);
    }

    @Override
    public List<ModelRelationDO> getRelationsByTargetModelCode(String targetModelCode) {
        return modelRelationMapper.selectByTargetModelCode(targetModelCode);
    }

    @Override
    public List<ModelRelationDO> getAllRelationsByModelCode(String modelCode) {
        List<ModelRelationDO> result = new ArrayList<>();
        result.addAll(getRelationsBySourceModelCode(modelCode));
        result.addAll(getRelationsByTargetModelCode(modelCode));
        return result;
    }

    @Override
    public ModelRelationDO getRelation(String sourceModelCode, String targetModelCode) {
        // 1. 获取源 Model
        ModelDO sourceModel = modelMapper.selectByCode(sourceModelCode);
        if (sourceModel == null) {
            return null;
        }

        // 2. 获取目标 Model
        ModelDO targetModel = modelMapper.selectByCode(targetModelCode);
        if (targetModel == null) {
            return null;
        }

        // 3. 查询关联
        return modelRelationMapper.selectBySourceAndTargetModelId(sourceModel.getId(), targetModel.getId());
    }

    @Override
    public boolean existsRelation(String sourceModelCode, String targetModelCode) {
        return getRelation(sourceModelCode, targetModelCode) != null;
    }

    @Override
    public List<ModelRelationDO> getRelationsByEntityTypeRelationId(Long entityTypeRelationId) {
        return modelRelationMapper.selectByEntityTypeRelationId(entityTypeRelationId);
    }

    @Override
    public List<ModelRelationDO> getAutoGeneratedRelations() {
        return modelRelationMapper.selectAutoGeneratedRelations();
    }

    @Override
    public List<ModelRelationDO> getManualCreatedRelations() {
        return modelRelationMapper.selectManualCreatedRelations();
    }

    @Override
    public ModelRelationDO getRelationById(Long id) {
        return modelRelationMapper.selectById(id);
    }

    // ========== 私有方法 ==========

    /**
     * 生成关联名称
     * 规则：关联 + 目标 Model 名称
     * 
     * 需求：BR-REL-002-2
     */
    private String generateRelationName(ModelDO targetModel) {
        return "关联" + targetModel.getName();
    }

    /**
     * 生成关联字段编码
     * 规则：目标 Model 编码 + _id
     * 
     * 需求：BR-REL-002-1
     */
    private String generateFieldCode(ModelDO targetModel) {
        // 将编码中的连字符替换为下划线，并添加 _id 后缀
        return targetModel.getCode().replace("-", "_") + "_id";
    }

    /**
     * 生成反向关联字段编码
     * 
     * 用于创建target model指向source model的REF字段
     * 字段编码规则：源 Model 编码 + "_id"
     * 
     * @param sourceModel 源 Model
     * @return 反向字段编码
     */
    private String generateReverseFieldCode(ModelDO sourceModel) {
        // 将编码中的连字符替换为下划线，并添加 _id 后缀
        return sourceModel.getCode().replace("-", "_") + "_id";
    }

    /**
     * 生成反向关联名称
     * 
     * 用于创建target model指向source model的REF字段
     * 关联名称规则："关联" + 源 Model 名称（如"关联设备"）
     * 
     * @param sourceModel 源 Model
     * @return 反向关联名称
     */
    private String generateReverseRelationName(ModelDO sourceModel) {
        // 关联名称规则："关联" + 源 Model 名称
        return "关联" + sourceModel.getName();
    }

    /**
     * 获取当前租户ID
     */
    private Long getTenantId() {
        return Objects.requireNonNullElse(TenantContextHolder.getRequiredTenantId(), 0L);
    }
}
