package cn.cheers.x.module.dynamicbusiness.service.model;

import cn.cheers.x.module.dynamicbusiness.dal.dataobject.model.ModelRelationDO;

import java.util.List;

/**
 * Model 关联服务接口
 * 
 * 业务含义：管理 Model 之间的关联关系，支持正向查询和反向查询。
 * 
 * 两层关联架构：
 * 1. 第一层（用户操作层）：BusinessType 级别关联，由 BusinessTypeRelationService 管理
 * 2. 第二层（系统执行层）：Model 级别关联，由本服务管理
 * 
 * 关联来源：
 * - 自动生成：由系统根据 BusinessType 关联自动展开生成
 * - 手动创建：用户直接在 Model 级别创建的关联
 * 
 * 需求：FR-075, FR-076, FR-080
 * 
 * @author yudao
 */
public interface ModelRelationService {

    /**
     * 创建 Model 关联
     * 
     * 在源 Model 和目标 Model 之间建立关联关系。
     * 系统会自动为源 Model 创建关联字段（ENTITY_REF 类型）。
     * 
     * 关联字段规则：
     * - 字段编码：目标 Model 编码 + "_id"（如 plan_id）
     * - 字段名称："所属" + 目标 Model 名称（如"所属计划"）
     * - 字段类型：ENTITY_REF
     * - 可查询：true
     * 
     * @param sourceModelCode 源 Model 编码
     * @param targetModelCode 目标 Model 编码
     * @param relationName 关联名称（可选，默认为"所属" + 目标 Model 名称）
     * @param autoGenerated 是否为系统自动生成
     * @param businessTypeRelationId 来源的 BusinessType 关联 ID（自动生成时必填）
     * @return 关联 ID
     */
    Long createRelation(String sourceModelCode, String targetModelCode, 
                        String relationName, Boolean autoGenerated, Long businessTypeRelationId);

    /**
     * 删除 Model 关联
     * 
     * 删除源 Model 和目标 Model 之间的关联关系。
     * 注意：不会删除已创建的关联字段，以保护已有数据。
     * 
     * @param sourceModelCode 源 Model 编码
     * @param targetModelCode 目标 Model 编码
     */
    void deleteRelation(String sourceModelCode, String targetModelCode);

    /**
     * 根据 ID 删除 Model 关联
     * 
     * @param id 关联 ID
     */
    void deleteRelationById(Long id);

    /**
     * 根据 BusinessType 关联 ID 删除所有自动生成的 Model 关联
     * 
     * 当用户删除 BusinessType 关联时，系统自动调用此方法清理相关的 Model 关联。
     * 
     * @param businessTypeRelationId BusinessType 关联 ID
     * @return 删除的关联数量
     */
    int deleteByBusinessTypeRelationId(Long businessTypeRelationId);

    /**
     * 获取源 Model 的所有关联列表
     * 
     * 查询从指定 Model 出发的所有关联（正向关联）。
     * 
     * @param sourceModelCode 源 Model 编码
     * @return 关联列表
     */
    List<ModelRelationDO> getRelationsBySourceModelCode(String sourceModelCode);

    /**
     * 获取目标 Model 的所有关联列表
     * 
     * 查询指向指定 Model 的所有关联（反向关联）。
     * 用于反向查询场景，如查询哪些 Model 关联到了指定 Model。
     * 
     * @param targetModelCode 目标 Model 编码
     * @return 关联列表
     */
    List<ModelRelationDO> getRelationsByTargetModelCode(String targetModelCode);

    /**
     * 获取 Model 的所有关联列表（包括正向和反向）
     * 
     * @param modelCode Model 编码
     * @return 关联列表
     */
    List<ModelRelationDO> getAllRelationsByModelCode(String modelCode);

    /**
     * 获取指定的 Model 关联
     * 
     * @param sourceModelCode 源 Model 编码
     * @param targetModelCode 目标 Model 编码
     * @return 关联信息，不存在时返回 null
     */
    ModelRelationDO getRelation(String sourceModelCode, String targetModelCode);

    /**
     * 检查 Model 关联是否存在
     * 
     * @param sourceModelCode 源 Model 编码
     * @param targetModelCode 目标 Model 编码
     * @return 是否存在
     */
    boolean existsRelation(String sourceModelCode, String targetModelCode);

    /**
     * 根据 BusinessType 关联 ID 获取所有 Model 关联
     * 
     * @param businessTypeRelationId BusinessType 关联 ID
     * @return 关联列表
     */
    List<ModelRelationDO> getRelationsByBusinessTypeRelationId(Long businessTypeRelationId);

    /**
     * 获取所有自动生成的关联
     * 
     * @return 自动生成的关联列表
     */
    List<ModelRelationDO> getAutoGeneratedRelations();

    /**
     * 获取所有手动创建的关联
     * 
     * @return 手动创建的关联列表
     */
    List<ModelRelationDO> getManualCreatedRelations();

    /**
     * 根据 ID 获取 Model 关联
     * 
     * @param id 关联 ID
     * @return 关联信息，不存在时返回 null
     */
    ModelRelationDO getRelationById(Long id);
}
