package cn.cheers.x.module.dynamicbusiness.controller.admin.model.vo;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Model 关联响应 VO
 * 
 * @author yudao
 */
@Schema(description = "管理后台 - Model 关联响应 VO")
@Data
public class ModelRelationRespVO {

    @Schema(description = "关联 ID", requiredMode = Schema.RequiredMode.REQUIRED, example = "1")
    private Long id;

    @Schema(description = "来源的 BusinessType 关联 ID（可为空，表示手动创建）", example = "1")
    private Long businessTypeRelationId;

    @Schema(description = "源 Model ID", requiredMode = Schema.RequiredMode.REQUIRED, example = "10")
    private Long sourceModelId;

    @Schema(description = "源 Model 编码", requiredMode = Schema.RequiredMode.REQUIRED, example = "task")
    private String sourceModelCode;

    @Schema(description = "源 Model 名称", example = "任务")
    private String sourceModelName;

    @Schema(description = "目标 Model ID", requiredMode = Schema.RequiredMode.REQUIRED, example = "20")
    private Long targetModelId;

    @Schema(description = "目标 Model 编码", requiredMode = Schema.RequiredMode.REQUIRED, example = "plan")
    private String targetModelCode;

    @Schema(description = "目标 Model 名称", example = "计划")
    private String targetModelName;

    @Schema(description = "关联名称", requiredMode = Schema.RequiredMode.REQUIRED, example = "所属计划")
    private String relationName;

    @Schema(description = "关联字段编码", requiredMode = Schema.RequiredMode.REQUIRED, example = "plan_id")
    private String fieldCode;

    @Schema(description = "是否系统自动生成", requiredMode = Schema.RequiredMode.REQUIRED, example = "true")
    private Boolean autoGenerated;

    @Schema(description = "创建时间", requiredMode = Schema.RequiredMode.REQUIRED)
    private LocalDateTime createTime;
}
