#!/usr/bin/env python3
"""
将历史 zhgl CAT-* 设备分类合并到 EQCAT-* 标准库。

1. 按旧分类名称映射到新叶子品类
2. 迁移 dynamic_model_category_relation（旧 MODEL-* 型号挂接）
3. 软删旧 CAT-* 分类节点

用法:
  python migrate_legacy_cat_to_eqcat.py --dry-run
  python migrate_legacy_cat_to_eqcat.py --apply
"""

from __future__ import annotations

import argparse
import os
import subprocess
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SEED_DIR = ROOT / "system" / "seed"
OUTPUT_SQL = SEED_DIR / "migrate_legacy_cat_to_eqcat.sql"
TENANT_ID = 1

# 旧分类 name → 新叶子 EQCAT-DEV code（按专业语义归并）
LEGACY_NAME_TO_EQCAT: dict[str, str] = {
    # 一级子系统（无型号直挂时，仅用于归档映射；有子节点时子节点优先）
    "安防系统": "EQCAT-L1-BMS",
    "电缆类": "EQCAT-DEV-CABLE-LV",
    "IP电话系统": "EQCAT-L2-ICT-VOICE",
    "光纤收发器": "EQCAT-DEV-MEDIA-CONVERTER",
    "无线对讲系统": "EQCAT-L2-ICT-RADIO",
    "人员定位系统": "EQCAT-L2-BMS-POSITION",
    "环控系统": "EQCAT-L2-INST-BACS",
    "大屏显示系统": "EQCAT-L2-BMS-DISPLAY",
    "机房环境监控": "EQCAT-L2-DCIM-MONITOR",
    "供配电系统": "EQCAT-L1-ELPW",
    "电力与配电系统": "EQCAT-L1-ELPW",
    "通风与给排水系统": "EQCAT-L1-PLUM",
    "消防系统": "EQCAT-L1-FIRE",
    "视频监控与安防": "EQCAT-L2-BMS-VIDEO",
    "通信与网络": "EQCAT-L1-ICT",
    "环境与检测": "EQCAT-L2-INST-ENV",
    # 设备级 / 叶子
    "传感器类": "EQCAT-L2-INST-ENV",
    "二氧化碳检测仪": "EQCAT-DEV-SENSOR-CO2",
    "氧气检测仪": "EQCAT-DEV-SENSOR-O2",
    "温湿度检测仪": "EQCAT-DEV-SENSOR-TH",
    "阀门": "EQCAT-DEV-VALVE-GATE",
    "控制箱": "EQCAT-DEV-CTRL-BOX",
    "按钮箱": "EQCAT-DEV-BUTTON-BOX",
    "照明": "EQCAT-DEV-LIGHTING",
    "人员定位主机": "EQCAT-DEV-POS-READER",
    "气溶胶": "EQCAT-DEV-AEROSOL",
    "门禁控制器": "EQCAT-DEV-ACCESS-CTRL",
    "功分器": "EQCAT-DEV-RADIO-SPLITTER",
    "网络设备": "EQCAT-DEV-SW-ACCESS",
    "ACU柜": "EQCAT-DEV-ACU",
    "水泵": "EQCAT-DEV-PUMP-SUPPLY",
    "无线远端机": "EQCAT-DEV-RADIO-REMOTE",
    "检修箱": "EQCAT-DEV-MAINT-BOX",
    "温湿度传感器": "EQCAT-DEV-SENSOR-TH",
    "移动终端": "EQCAT-DEV-POS-TERMINAL",
    "报警主机": "EQCAT-DEV-ALARM-HOST",
    "网络摄像机": "EQCAT-DEV-CAMERA-IP",
    "定向天线": "EQCAT-DEV-RADIO-ANTENNA",
    "氧气传感器": "EQCAT-DEV-SENSOR-O2",
    "监控控制柜": "EQCAT-DEV-SECURITY-CABINET",
    "二氧化碳传感器": "EQCAT-DEV-SENSOR-CO2",
    "LED显示屏": "EQCAT-DEV-LED-PANEL",
    "红外探测器": "EQCAT-DEV-IR-DETECTOR",
    "环网交换机": "EQCAT-DEV-SW-RING",
}

# 旧型号 name 额外映射（名称与分类名不一致时）
LEGACY_MODEL_NAME_TO_EQCAT: dict[str, str] = {
    "给水泵": "EQCAT-DEV-PUMP-SUPPLY",
    "门禁": "EQCAT-DEV-ACCESS-CTRL",
    "应急灯": "EQCAT-DEV-EMERGENCY-LIGHT",
    "二氧化碳检测仪": "EQCAT-DEV-SENSOR-CO2",
    "温湿度检测仪": "EQCAT-DEV-SENSOR-TH",
    "温湿度传感器": "EQCAT-DEV-SENSOR-TH",
}


def fetch_legacy_categories() -> list[tuple[str, str]]:
    env = os.environ.copy()
    env["PGPASSWORD"] = env.get("PGPASSWORD", "Coolhomer")
    env["PGCLIENTENCODING"] = "UTF8"
    result = subprocess.run(
        [
            "psql", "-h", env.get("PGHOST", "127.0.0.1"), "-U", env.get("PGUSER", "postgres"),
            "-d", env.get("PGDATABASE", "sinopec"), "-t", "-A", "-F", "\t", "-c",
            "SET search_path TO dynamicbusiness; "
            "SELECT code, name FROM dynamic_category "
            "WHERE deleted=false AND tenant_id=1 AND category_type_code='equipment' "
            "AND code LIKE 'CAT-%' ORDER BY level, sort, id;",
        ],
        capture_output=True, text=True, encoding="utf-8", env=env, check=True,
    )
    rows: list[tuple[str, str]] = []
    for line in result.stdout.splitlines():
        if not line.strip() or line.startswith("SET"):
            continue
        code, name = line.split("\t", 1)
        rows.append((code, name))
    return rows


def build_sql(legacy_rows: list[tuple[str, str]]) -> str | None:
    if not legacy_rows:
        return None

    unmapped: list[str] = []
    mapping_cases: list[str] = []
    for old_code, old_name in legacy_rows:
        target = LEGACY_NAME_TO_EQCAT.get(old_name)
        if not target:
            unmapped.append(f"{old_code}\t{old_name}")
            continue
        mapping_cases.append(f"WHEN '{old_code}' THEN '{target}'")

    if unmapped:
        raise RuntimeError("Unmapped legacy categories:\n" + "\n".join(unmapped))

    model_cases = [f"WHEN '{k}' THEN '{v}'" for k, v in LEGACY_MODEL_NAME_TO_EQCAT.items()]

    model_values = ", ".join(f"('{k}', '{v}')" for k, v in LEGACY_MODEL_NAME_TO_EQCAT.items()) or "('__none__', 'EQCAT-DEV-UNCATEGORIZED')"

    return textwrap.dedent(
        f"""
        -- Merge legacy zhgl CAT-* equipment categories into EQCAT-* standard library
        -- Generated by migrate_legacy_cat_to_eqcat.py
        SET search_path TO dynamicbusiness;

        -- temp: old CAT code -> target category code (leaf or nearest node)
        CREATE TEMP TABLE legacy_cat_map (old_code text PRIMARY KEY, target_code text NOT NULL);
        INSERT INTO legacy_cat_map (old_code, target_code) VALUES
        {",".join(f"('{c}', '{LEGACY_NAME_TO_EQCAT[n]}')" for c, n in legacy_rows)};

        -- 1) migrate model-category relations from CAT to EQCAT
        UPDATE dynamic_model_category_relation r
        SET
          category_id = nc.id,
          category_code = nc.code,
          updater = 'migrate-legacy-cat',
          update_time = CURRENT_TIMESTAMP
        FROM legacy_cat_map m
        JOIN dynamic_category oc
          ON oc.deleted = false AND oc.tenant_id = {TENANT_ID} AND oc.code = m.old_code
        JOIN dynamic_category nc
          ON nc.deleted = false AND nc.tenant_id = {TENANT_ID} AND nc.code = m.target_code
        WHERE r.deleted = false AND r.tenant_id = {TENANT_ID}
          AND r.entity_type_code = 'equipment'
          AND r.category_id = oc.id
          AND r.category_code = oc.code;

        -- 2) legacy MODEL-* refined mapping by model name
        UPDATE dynamic_model_category_relation r
        SET
          category_id = nc.id,
          category_code = nc.code,
          updater = 'migrate-legacy-cat',
          update_time = CURRENT_TIMESTAMP
        FROM dynamic_model dm
        JOIN (
          VALUES
            {model_values}
        ) AS mm(model_name, target_code) ON mm.model_name = dm.name
        JOIN dynamic_category nc
          ON nc.deleted = false AND nc.tenant_id = {TENANT_ID} AND nc.code = mm.target_code
        WHERE r.deleted = false AND r.tenant_id = {TENANT_ID}
          AND r.entity_type_code = 'equipment'
          AND r.model_id = dm.id
          AND dm.deleted = false AND dm.entity_type_code = 'equipment'
          AND dm.code LIKE 'MODEL-%';

        -- 3) remove leftover CAT relations
        -- 4) soft-delete legacy CAT categories
        -- 5) rebuild tree_path
        UPDATE dynamic_model_category_relation r
        SET deleted = true, updater = 'migrate-legacy-cat', update_time = CURRENT_TIMESTAMP
        WHERE r.deleted = false AND r.tenant_id = {TENANT_ID}
          AND r.entity_type_code = 'equipment'
          AND r.category_code LIKE 'CAT-%';

        -- 4) 软删旧 CAT-* 分类
        UPDATE dynamic_category c
        SET deleted = true, updater = 'migrate-legacy-cat', update_time = CURRENT_TIMESTAMP
        WHERE c.deleted = false AND c.tenant_id = {TENANT_ID}
          AND c.category_type_code = 'equipment'
          AND c.code LIKE 'CAT-%';

        -- 5) 重建树路径
        WITH RECURSIVE cat_tree AS (
          SELECT c.id, c.code, c.parent_id, ARRAY[c.id] AS path_ids, 0 AS lvl
          FROM dynamic_category c
          WHERE c.deleted = false AND c.tenant_id = {TENANT_ID}
            AND c.category_type_code = 'equipment'
            AND (c.parent_id IS NULL OR c.parent_id = 0
                 OR NOT EXISTS (
                   SELECT 1 FROM dynamic_category p
                   WHERE p.id = c.parent_id AND p.deleted = false AND p.tenant_id = {TENANT_ID}
                 ))
          UNION ALL
          SELECT c.id, c.code, c.parent_id, ct.path_ids || c.id, ct.lvl + 1
          FROM dynamic_category c
          JOIN cat_tree ct ON c.parent_id = ct.id
          WHERE c.deleted = false AND c.tenant_id = {TENANT_ID}
            AND c.category_type_code = 'equipment'
        )
        UPDATE dynamic_category c
        SET tree_path = ct.path_ids, level = ct.lvl + 1
        FROM cat_tree ct
        WHERE c.id = ct.id AND c.category_type_code = 'equipment';
        """
    ).strip() + "\n"


def apply_sql(sql: str) -> None:
    env = os.environ.copy()
    env["PGPASSWORD"] = env.get("PGPASSWORD", "Coolhomer")
    env["PGCLIENTENCODING"] = "UTF8"
    OUTPUT_SQL.write_text(sql, encoding="utf-8")
    subprocess.run(
        [
            "psql",
            "-h",
            env.get("PGHOST", "127.0.0.1"),
            "-U",
            env.get("PGUSER", "postgres"),
            "-d",
            env.get("PGDATABASE", "sinopec"),
            "-v",
            "ON_ERROR_STOP=1",
            "--no-psqlrc",
            "-f",
            str(OUTPUT_SQL),
        ],
        check=True,
        env=env,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    legacy = fetch_legacy_categories()
    if not legacy:
        print(f"No legacy CAT-* categories; {OUTPUT_SQL.name} not needed")
        if args.apply:
            print("Migration skipped (already merged)")
        return

    sql = build_sql(legacy)
    OUTPUT_SQL.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUTPUT_SQL.name} ({len(legacy)} legacy categories mapped)")

    if args.apply:
        apply_sql(sql)
        print("Applied migration to database")
    elif not args.dry_run:
        print("Use --apply to execute, or run psql -f on the generated SQL")


if __name__ == "__main__":
    main()
