CREATE SCHEMA IF NOT EXISTS twin;

CREATE TABLE IF NOT EXISTS twin.twin_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_code VARCHAR(64) NOT NULL,
    mapping_type SMALLINT NOT NULL DEFAULT 1,
    relation_mode SMALLINT NOT NULL DEFAULT 1,
    facility_id BIGINT NOT NULL,
    actor_instance_id BIGINT NOT NULL,
    scene_id BIGINT,
    scene_code VARCHAR(64),
    bind_source VARCHAR(32),
    status SMALLINT NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    ext_json JSONB,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator VARCHAR(64) NOT NULL DEFAULT '',
    updater VARCHAR(64) NOT NULL DEFAULT '',
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_twin_mapping_code
    ON twin.twin_mapping (mapping_code);
CREATE INDEX IF NOT EXISTS idx_twin_mapping_facility_active
    ON twin.twin_mapping (facility_id, relation_mode, status, deleted);
CREATE INDEX IF NOT EXISTS idx_twin_mapping_actor_active
    ON twin.twin_mapping (actor_instance_id, relation_mode, status, deleted);
CREATE INDEX IF NOT EXISTS idx_twin_mapping_scene_active
    ON twin.twin_mapping (scene_id, status, deleted);
CREATE INDEX IF NOT EXISTS idx_twin_mapping_scene_code_active
    ON twin.twin_mapping (scene_code, status, deleted);

COMMENT ON TABLE twin.twin_mapping IS 'Twin 映射主表';
COMMENT ON COLUMN twin.twin_mapping.mapping_code IS '映射编码';
COMMENT ON COLUMN twin.twin_mapping.mapping_type IS '映射类型：1=Facility-ActorInstance';
COMMENT ON COLUMN twin.twin_mapping.relation_mode IS '关系模式：1=1:1主绑定';
COMMENT ON COLUMN twin.twin_mapping.facility_id IS '设施ID';
COMMENT ON COLUMN twin.twin_mapping.actor_instance_id IS 'Actor实例ID';
COMMENT ON COLUMN twin.twin_mapping.scene_id IS '场景ID';
COMMENT ON COLUMN twin.twin_mapping.scene_code IS '场景编码';
COMMENT ON COLUMN twin.twin_mapping.bind_source IS '绑定来源';
COMMENT ON COLUMN twin.twin_mapping.status IS '状态：1=有效 0=失效';
COMMENT ON COLUMN twin.twin_mapping.version IS '乐观锁版本';
COMMENT ON COLUMN twin.twin_mapping.remark IS '备注';
COMMENT ON COLUMN twin.twin_mapping.ext_json IS '扩展信息';
