-- 数据管理页：按 entity_type_code 配置分类/模型/实体/详情浏览维

SET search_path TO dynamicbusiness;

CREATE TABLE IF NOT EXISTS dynamicbusiness.dm_entity_dimension (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint DEFAULT 0 NOT NULL,
    entity_type_code character varying(64) NOT NULL,
    dimension_kind character varying(32) NOT NULL,
    perspective_id character varying(64),
    props_id bigint,
    enabled boolean DEFAULT true NOT NULL,
    category_dimension_meta jsonb,
    creator character varying(64),
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updater character varying(64),
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted boolean DEFAULT false NOT NULL
);

COMMENT ON TABLE dynamicbusiness.dm_entity_dimension IS '数据管理·实体浏览维度（dm_ 前缀，索引 entity_type_code）';
COMMENT ON COLUMN dynamicbusiness.dm_entity_dimension.entity_type_code IS '关联 dynamic_entity_type.code';
COMMENT ON COLUMN dynamicbusiness.dm_entity_dimension.dimension_kind IS 'CATEGORY|MODEL|ENTITY|DETAIL';
COMMENT ON COLUMN dynamicbusiness.dm_entity_dimension.perspective_id IS '仅 CATEGORY 多 Tab 视角 id';
COMMENT ON COLUMN dynamicbusiness.dm_entity_dimension.props_id IS 'pr_component_props.id';
COMMENT ON COLUMN dynamicbusiness.dm_entity_dimension.category_dimension_meta IS '仅 CATEGORY：label/categoryTypeCode/treeSemantics/displayMode';

CREATE UNIQUE INDEX IF NOT EXISTS uk_dm_entity_dimension_scope
    ON dynamicbusiness.dm_entity_dimension (tenant_id, entity_type_code, dimension_kind, COALESCE(perspective_id, ''))
    WHERE deleted = false;

CREATE INDEX IF NOT EXISTS idx_dm_entity_dimension_entity_type
    ON dynamicbusiness.dm_entity_dimension (tenant_id, entity_type_code)
    WHERE deleted = false;
