<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.cloud</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-alarm-api</module>
        <module>yudao-module-alarm-biz</module>
    </modules>
    <artifactId>yudao-module-alarm</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        alarm 模块，提供告警管理功能。
        包括：告警触发、告警处理、联动控制、告警规则配置、告警统计等
    </description>

</project>
