package cn.cheers.x.module.dynamicbusiness.controller.admin.relation.vo.bidirectional;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * 关联实体 VO
 * 
 * <p>用于展示关联关系中的实体信息，包括正向和反向关联。</p>
 * 
 * @author yudao
 */
@Schema(description = "管理后台 - 关联实体 Response VO")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RelatedEntityVO {

    @Schema(description = "关联的 Model 编码", requiredMode = Schema.RequiredMode.REQUIRED, example = "production_task")
    private String modelCode;

    @Schema(description = "关联的 Model 名称", requiredMode = Schema.RequiredMode.REQUIRED, example = "生产任务")
    private String modelName;

    @Schema(description = "关联字段编码", requiredMode = Schema.RequiredMode.REQUIRED, example = "plan_id")
    private String fieldCode;

    @Schema(description = "关联字段名称", requiredMode = Schema.RequiredMode.REQUIRED, example = "所属计划")
    private String fieldName;

    @Schema(description = "关联的实体数量", requiredMode = Schema.RequiredMode.REQUIRED, example = "8")
    private Long count;

    @Schema(description = "关联的实体列表（可选，分页获取）")
    private List<EntitySimpleVO> entities;

    @Schema(description = "是否系统自动生成", example = "true")
    private Boolean autoGenerated;

    @Schema(description = "业务类型编码", example = "task")
    private String businessTypeCode;

    @Schema(description = "业务类型名称", example = "任务管理")
    private String businessTypeName;
}
