spring:
  application:
    name: maintenance-server

  profiles:
    active: local

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml

  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 32MB

  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
      write-durations-as-timestamps: true
      fail-on-empty-beans: false

  cache:
    type: REDIS
    redis:
      time-to-live: 1h

server:
  port: 58111

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log

--- #################### 接口文档配置 ####################

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: NONE
      logic-delete-value: true
      logic-not-delete-value: false
    banner: false
  type-aliases-package: cn.cheers.x.maintenance.dal.dataobject
  encryptor:
    password: XDV71a+xqStEA3WH

mybatis-plus-join:
  banner: false

spring:
  data:
    redis:
      repositories:
        enabled: false

easy-trans:
  is-enable-global: false

cheers:
  info:
    version: 1.0.0
    base-package: cn.cheers.x.maintenance
  web:
    admin-ui:
      url: http://dashboard.local
  xss:
    enable: false
    exclude-urls:
      - ${management.endpoints.web.base-path}/**
  swagger:
    title: 维护手册管理
    description: 提供维护手册、绑定、日历与故障主流程能力
    version: ${cheers.info.version}
  tenant:
    enable: true
    ignore-urls:
    ignore-visit-urls:
    ignore-tables:
    ignore-caches:

debug: false
