spring:
  application:
    name: platformtopology-server
  ai:
    mcp:
      client:
        enabled: false
        annotation-scanner:
          enabled: false
  profiles:
    active: local
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 32MB
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
      write-durations-as-timestamps: true
      fail-on-empty-beans: false
  cache:
    type: REDIS
    redis:
      time-to-live: 1h
  data:
    redis:
      repositories:
        enabled: false
  kafka:
    producer:
      acks: 1
      retries: 3
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    listener:
      missing-topics-fatal: false

server:
  port: 58107

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log
  level:
    cn.cheers.x.module.platform.topology.dal.mysql: INFO
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR

--- #################### Cheers 相关配置 ####################

cheers:
  tenant:
    enable: true
    ignore-urls:
      - /admin-api/system/tenant/**
      - /admin-api/system/user/profile/**
      - /admin-api/system/auth/**
    ignore-visit-urls:
      - /admin-api/system/tenant/**
      - /admin-api/system/user/profile/**
      - /admin-api/system/auth/**
  env:
    tag: ${HOSTNAME}
  captcha:
    enable: false
  security:
    mock-enable: true
  access-log:
    enable: true

--- #################### 接口文档配置 ####################

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: NONE
      logic-delete-value: true
      logic-not-delete-value: false
    banner: false
  type-aliases-package: ${cheers.info.base-package}.dal.dataobject
  encryptor:
    password: XDV71a+xqStEA3WH

mybatis-plus-join:
  banner: false

easy-trans:
  is-enable-global: false

--- #################### RPC 远程调用相关配置 ####################

--- #################### 消息队列相关 ####################

rocketmq:
  producer:
    group: ${spring.application.name}_PRODUCER

--- #################### 定时任务相关配置 ####################

xxl:
  job:
    executor:
      appname: ${spring.application.name}
      logpath: ${user.home}/logs/xxl-job/${spring.application.name}
    accessToken: default_token

--- #################### 验证码相关配置 ####################

aj:
  captcha:
    jigsaw: classpath:images/jigsaw
    pic-click: classpath:images/pic-click
    cache-type: redis
    cache-number: 1000
    timing-clear: 180
    type: blockPuzzle
    water-mark: cheers
    interference-options: 0
    req-frequency-limit-enable: false
    req-get-lock-limit: 5
    req-get-lock-seconds: 10
    req-get-minute-limit: 30
    req-check-minute-limit: 60
    req-verify-minute-limit: 60

--- #################### Cheers 相关配置 ####################

cheers:
  info:
    version: 1.0.0
    base-package: cn.cheers.x.module.platform.topology
  web:
    admin-ui:
      url: http://dashboard.local
  xss:
    enable: false
    exclude-urls:
      - ${management.endpoints.web.base-path}/**
  api-encrypt:
    enable: true
    algorithm: AES
    request-key: 52549111389893486934626385991395
    response-key: 96103715984234343991809655248883
  swagger:
    title: 管理后台
    description: 提供管理员管理的所有功能
    version: ${cheers.info.version}
  tenant:
    enable: true
    ignore-urls:
      - /admin-api/system/tenant/**
      - /admin-api/system/user/profile/**
      - /admin-api/system/auth/**
    ignore-visit-urls:
      - /admin-api/system/tenant/**
      - /admin-api/system/user/profile/**
      - /admin-api/system/auth/**
    ignore-tables:
      - platform_policy_template
      - platform_mobility_profile
    ignore-caches:
      - user_role_ids
      - permission_menu_ids
      - oauth_client
      - notify_template
      - mail_account
      - mail_template
      - sms_template
  sms-code:
    expire-times: 10m
    send-frequency: 1m
    send-maximum-quantity-per-day: 10
    begin-code: 9999
    end-code: 9999

debug: false
