<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.cheers.x</groupId>
        <artifactId>cheers</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>cn.cheers.x</groupId>
    <artifactId>cheers-infra</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>cheers-infra-api</module>
        <module>cheers-infra-server</module>
    </modules>
    <name>${project.artifactId}</name>
    <description>
        infra 模块：基础设施运维与管理，以及研发工具（定时任务、文件、代码生成等）。
    </description>
</project>
