package cn.cheers.x.module.dynamicbusiness.controller.admin.relation.vo.bidirectional;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 关联发现结果 VO
 * 
 * <p>用于展示发现的关联关系信息。</p>
 * 
 * @author yudao
 */
@Schema(description = "管理后台 - 关联发现结果 Response VO")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RelationDiscoveryVO {

    @Schema(description = "源 Model ID", requiredMode = Schema.RequiredMode.REQUIRED, example = "100")
    private Long sourceModelId;

    @Schema(description = "源 Model 编码", requiredMode = Schema.RequiredMode.REQUIRED, example = "production_task")
    private String sourceModelCode;

    @Schema(description = "源 Model 名称", requiredMode = Schema.RequiredMode.REQUIRED, example = "生产任务")
    private String sourceModelName;

    @Schema(description = "源业务类型编码", example = "task")
    private String sourceEntityTypeCode;

    @Schema(description = "源业务类型名称", example = "任务管理")
    private String sourceEntityTypeName;

    @Schema(description = "关联字段 ID", requiredMode = Schema.RequiredMode.REQUIRED, example = "200")
    private Long fieldId;

    @Schema(description = "关联字段编码", requiredMode = Schema.RequiredMode.REQUIRED, example = "plan_id")
    private String fieldCode;

    @Schema(description = "关联字段名称", requiredMode = Schema.RequiredMode.REQUIRED, example = "所属计划")
    private String fieldName;

    @Schema(description = "目标 Model 编码", example = "production_plan")
    private String targetModelCode;

    @Schema(description = "目标 Model 名称", example = "生产计划")
    private String targetModelName;

    @Schema(description = "是否系统自动生成", example = "true")
    private Boolean autoGenerated;

    @Schema(description = "关联字段库 ID（如果来自字段库）", example = "50")
    private Long refLibraryId;
}
