package cn.cheers.x.module.dynamicbusiness.dal.mysql.model;

import cn.iocoder.yudao.framework.mybatis.core.mapper.BaseMapperX;
import cn.iocoder.yudao.framework.mybatis.core.query.LambdaQueryWrapperX;
import cn.cheers.x.module.dynamicbusiness.dal.dataobject.model.ModelRelationDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Delete;

import java.util.List;

/**
 * Model 关联 Mapper
 *
 * @author yudao
 */
@Mapper
public interface ModelRelationMapper extends BaseMapperX<ModelRelationDO> {

    /**
     * 根据源 Model ID 查询关联列表
     */
    default List<ModelRelationDO> selectBySourceModelId(Long sourceModelId) {
        return selectList(new LambdaQueryWrapperX<ModelRelationDO>()
                .eq(ModelRelationDO::getSourceModelId, sourceModelId)
                .orderByDesc(ModelRelationDO::getCreateTime));
    }

    /**
     * 根据目标 Model ID 查询关联列表
     */
    default List<ModelRelationDO> selectByTargetModelId(Long targetModelId) {
        return selectList(new LambdaQueryWrapperX<ModelRelationDO>()
                .eq(ModelRelationDO::getTargetModelId, targetModelId)
                .orderByDesc(ModelRelationDO::getCreateTime));
    }

    /**
     * 根据源 Model 编码查询关联列表
     */
    default List<ModelRelationDO> selectBySourceModelCode(String sourceModelCode) {
        return selectList(new LambdaQueryWrapperX<ModelRelationDO>()
                .eq(ModelRelationDO::getSourceModelCode, sourceModelCode)
                .orderByDesc(ModelRelationDO::getCreateTime));
    }

    /**
     * 根据目标 Model 编码查询关联列表
     */
    default List<ModelRelationDO> selectByTargetModelCode(String targetModelCode) {
        return selectList(new LambdaQueryWrapperX<ModelRelationDO>()
                .eq(ModelRelationDO::getTargetModelCode, targetModelCode)
                .orderByDesc(ModelRelationDO::getCreateTime));
    }

    /**
     * 根据源和目标 Model ID 查询关联
     */
    default ModelRelationDO selectBySourceAndTargetModelId(Long sourceModelId, Long targetModelId) {
        return selectOne(new LambdaQueryWrapperX<ModelRelationDO>()
                .eq(ModelRelationDO::getSourceModelId, sourceModelId)
                .eq(ModelRelationDO::getTargetModelId, targetModelId));
    }

    /**
     * 根据 EntityType 关联 ID 查询所有 Model 关联
     */
    default List<ModelRelationDO> selectByEntityTypeRelationId(Long entityTypeRelationId) {
        return selectList(new LambdaQueryWrapperX<ModelRelationDO>()
                .eq(ModelRelationDO::getEntityTypeRelationId, entityTypeRelationId)
                .orderByDesc(ModelRelationDO::getCreateTime));
    }

    /**
     * 查询自动生成的关联列表
     */
    default List<ModelRelationDO> selectAutoGeneratedRelations() {
        return selectList(new LambdaQueryWrapperX<ModelRelationDO>()
                .eq(ModelRelationDO::getAutoGenerated, true)
                .orderByDesc(ModelRelationDO::getCreateTime));
    }

    /**
     * 查询手动创建的关联列表
     */
    default List<ModelRelationDO> selectManualCreatedRelations() {
        return selectList(new LambdaQueryWrapperX<ModelRelationDO>()
                .eq(ModelRelationDO::getAutoGenerated, false)
                .orderByDesc(ModelRelationDO::getCreateTime));
    }

    /**
     * 检查关联是否存在
     */
    default boolean existsBySourceAndTargetModelId(Long sourceModelId, Long targetModelId) {
        return selectCount(new LambdaQueryWrapperX<ModelRelationDO>()
                .eq(ModelRelationDO::getSourceModelId, sourceModelId)
                .eq(ModelRelationDO::getTargetModelId, targetModelId)) > 0;
    }

    /**
     * 根据 EntityType 关联 ID 删除所有自动生成的 Model 关联
     * 
     * 注意：使用物理删除，因为这些关联是系统自动生成的
     */
    @Delete("DELETE FROM dynamic_model_relation WHERE entity_type_relation_id = #{entityTypeRelationId} AND auto_generated = true")
    int deleteByEntityTypeRelationId(@Param("entityTypeRelationId") Long entityTypeRelationId);

    /**
     * 根据 Model ID 删除所有相关关联（源或目标）
     */
    default int deleteByModelId(Long modelId) {
        return delete(new LambdaQueryWrapperX<ModelRelationDO>()
                .and(w -> w
                        .eq(ModelRelationDO::getSourceModelId, modelId)
                        .or()
                        .eq(ModelRelationDO::getTargetModelId, modelId)));
    }

    /**
     * 根据字段编码查询关联
     */
    default ModelRelationDO selectByFieldCode(Long sourceModelId, String fieldCode) {
        return selectOne(new LambdaQueryWrapperX<ModelRelationDO>()
                .eq(ModelRelationDO::getSourceModelId, sourceModelId)
                .eq(ModelRelationDO::getFieldCode, fieldCode));
    }
}
