-- 「模型管理」左侧分类栏独立存储；从数据 Tab 布局表迁出并删除寄生列

SET search_path TO dynamicbusiness;

CREATE TABLE IF NOT EXISTS dynamicbusiness.dm_model_tab_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint DEFAULT 0 NOT NULL,
    entity_type_code character varying(64) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    label character varying(128),
    category_type_code character varying(64),
    props_id bigint,
    creator character varying(64),
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updater character varying(64),
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted boolean DEFAULT false NOT NULL
);

COMMENT ON TABLE dynamicbusiness.dm_model_tab_category IS '数据管理·模型管理 Tab 左侧分类栏（按数据类型一行）';
COMMENT ON COLUMN dynamicbusiness.dm_model_tab_category.entity_type_code IS '关联 dynamic_entity_type.code（registry）';
COMMENT ON COLUMN dynamicbusiness.dm_model_tab_category.category_type_code IS '分类种类编码';
COMMENT ON COLUMN dynamicbusiness.dm_model_tab_category.props_id IS '分类树组件 propsId';

CREATE UNIQUE INDEX IF NOT EXISTS uk_dm_model_tab_category_entity
    ON dynamicbusiness.dm_model_tab_category (tenant_id, entity_type_code)
    WHERE deleted = false;

-- 从布局表 MODEL 行的 model_tab_category JSON 迁出（仅有效行）
INSERT INTO dynamicbusiness.dm_model_tab_category (
    tenant_id, entity_type_code, enabled, label, category_type_code, props_id,
    creator, create_time, updater, update_time, deleted
)
SELECT
    d.tenant_id,
    d.entity_type_code,
    COALESCE((d.model_tab_category->>'enabled')::boolean, true),
    NULLIF(TRIM(d.model_tab_category->>'label'), ''),
    NULLIF(TRIM(d.model_tab_category->>'categoryTypeCode'), ''),
    CASE
        WHEN (d.model_tab_category->>'propsId') ~ '^[0-9]+$'
            THEN (d.model_tab_category->>'propsId')::bigint
        ELSE NULL
    END,
    d.creator,
    COALESCE(d.create_time, CURRENT_TIMESTAMP),
    d.updater,
    COALESCE(d.update_time, CURRENT_TIMESTAMP),
    false
FROM dynamicbusiness.dm_entity_dimension d
WHERE d.deleted = false
  AND d.column_kind = 'MODEL'
  AND d.model_tab_category IS NOT NULL
  AND d.model_tab_category <> 'null'::jsonb
  AND NOT EXISTS (
      SELECT 1
      FROM dynamicbusiness.dm_model_tab_category m
      WHERE m.tenant_id = d.tenant_id
        AND m.entity_type_code = d.entity_type_code
        AND m.deleted = false
  );

ALTER TABLE dynamicbusiness.dm_entity_dimension
    DROP COLUMN IF EXISTS model_tab_category;
