#!/usr/bin/env python3
"""生成按业务域组织的字段库 seed：物理清理旧字段 + 写入 field_library_catalog 定稿。

输出：
  platform-import/system/05_industry_field_library.sql
  ../cheers-module-dynamicbusiness-server/.../V27__init_industry_field_library.sql
"""
from __future__ import annotations

from pathlib import Path

from field_library_catalog import CATALOG, field_count, group_count

TENANT_ID = 1
SCRIPT_DIR = Path(__file__).resolve().parent
OUT_IMPORT = SCRIPT_DIR / "platform-import/system/05_industry_field_library.sql"
OUT_FLYWAY = (
    SCRIPT_DIR.parent
    / "cheers-module-dynamicbusiness-server/src/main/resources/db/migration/dynamicbusiness/V27__init_industry_field_library.sql"
)


def sql_literal(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def render_purge() -> str:
    return """
-- 物理清理旧字段及关联（按依赖顺序）
DELETE FROM dynamicbusiness.dynamic_group_relation
WHERE tenant_id = 1 AND group_type = 'FIELD';

DELETE FROM dynamicbusiness.dynamic_model_field_assignment
WHERE tenant_id = 1;

DELETE FROM dynamicbusiness.dynamic_template_field_assignment
WHERE tenant_id = 1;

DELETE FROM dynamicbusiness.dynamic_entity_field_permission
WHERE tenant_id = 1;

DELETE FROM dynamicbusiness.dynamic_dynamic_table_column c
USING dynamicbusiness.dynamic_field f
WHERE c.field_id = f.id AND f.tenant_id = 1;

DELETE FROM dynamicbusiness.dynamic_field WHERE tenant_id = 1;
DELETE FROM dynamicbusiness.dynamic_group WHERE tenant_id = 1 AND group_type = 'FIELD';
""".strip()


def render_groups() -> str:
    lines = [f"-- dynamic_group(FIELD): {group_count()} group(s)\n"]
    for group in CATALOG:
        lines.append(
            f"""
INSERT INTO dynamic_group (
  group_type, code, name, description, parent_id, path, level, sort, status, tenant_id, creator
) VALUES (
  'FIELD', {sql_literal(group.code)}, {sql_literal(group.name)}, {sql_literal(group.description)},
  NULL, NULL, 1, {group.sort}, 1, {TENANT_ID}, 'industry-field-library'
);
""".strip()
        )
    return "\n".join(lines)


def render_fields() -> str:
    lines = [f"-- dynamic_field: {field_count()} row(s), upsert by code\n"]
    for group in CATALOG:
        lines.append(f"\n-- [{group.name}]")
        for field in group.fields:
            lines.append(
                f"""
INSERT INTO dynamic_field (
  code, name, type, unit, description, source, status, max_relations,
  index_strategy, options, provider_code, semantic_type, tenant_id, creator
) VALUES (
  {sql_literal(field.code)}, {sql_literal(field.name)}, {sql_literal(field.type)},
  {sql_literal(field.unit)}, {sql_literal(field.description)},
  'SYSTEM', 1,
  NULL, 'NONE',
  {sql_literal(field.options)}, NULL,
  NULL, {TENANT_ID}, 'industry-field-library'
);
""".strip()
            )
    return "\n".join(lines)


def render_relations() -> str:
    lines = [f"-- dynamic_group_relation: {field_count()} row(s)\n"]
    sort = 0
    for group in CATALOG:
        for field in group.fields:
            sort += 10
            lines.append(
                f"""
INSERT INTO dynamic_group_relation (group_type, group_id, target_id, sort, tenant_id, creator)
SELECT 'FIELD', g.id, f.id, {sort}, {TENANT_ID}, 'industry-field-library'
FROM dynamic_group g
JOIN dynamic_field f ON f.deleted = false AND f.tenant_id = {TENANT_ID}
WHERE g.deleted = false AND g.tenant_id = {TENANT_ID} AND g.group_type = 'FIELD'
  AND g.code = {sql_literal(group.code)} AND f.code = {sql_literal(field.code)};
""".strip()
            )
    return "\n".join(lines)


def render_sql() -> str:
    header = f"""-- ============================================================================
-- 按业务域组织的字段库（物理重建）
-- Generated by scripts/generate-field-library.py
-- 分组 {group_count()} 个，字段 {field_count()} 个；每字段仅归属一个分组
-- 重新生成：python3 generate-field-library.py
-- ============================================================================

SET search_path TO dynamicbusiness;

{render_purge()}
"""
    return header + "\n\n" + render_groups() + "\n\n" + render_fields() + "\n\n" + render_relations() + "\n"


def main():
    sql = render_sql()
    OUT_IMPORT.parent.mkdir(parents=True, exist_ok=True)
    OUT_IMPORT.write_text(sql, encoding="utf-8")
    OUT_FLYWAY.write_text(sql.replace(
        "SET search_path TO dynamicbusiness;",
        "-- Flyway V27\nSET search_path TO dynamicbusiness;",
        1,
    ), encoding="utf-8")
    print(f"Groups: {group_count()}, Fields: {field_count()}")
    print(f"Wrote {OUT_IMPORT}")
    print(f"Wrote {OUT_FLYWAY}")


if __name__ == "__main__":
    main()
