<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.cheers.x</groupId>
        <artifactId>cheers-business-middle-platform</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>cheers-orchestration-api</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>platform-orchestration 模块 API</description>

    <dependencies>
        <dependency>
            <groupId>cn.cheers.x</groupId>
            <artifactId>cheers-common</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.cheers.x</groupId>
            <artifactId>cheers-contract-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
